language:       scala
scala:
              - 2.12.6
jdk:
              - openjdk8
              - oraclejdk8
dist:           trusty
cache:
  directories:
              - $HOME/.ivy2/cache
              - $HOME/.sbt/boot/
script:         ./sbt scripted
after_script:
              - find $HOME/.sbt -name "*.lock" | xargs rm
              - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
notifications:
  email:
    on_success: never
    on_failure: change
